/**
 * @file main.cpp
 * @brief superPod Single-MCU Unified Firmware Orchestrator.
 * 
 * =================================================================================
 * Architecture & Design Documentation:
 * =================================================================================
 * superPod unifies USB PL2303 transceiver emulation, Apple iPod Accessory Protocol
 * (espod Lingo engine), and Bluetooth Classic A2DP Sink audio streaming into a single
 * application running on the ESP32-S31.
 * 
 * Option B Swapped Dual-Core Task Allocation:
 *   - Core 0 (PRO_CPU): Dedicated Audio & Bluetooth Subsystem:
 *       * Low-level BT Controller Radio Task (Priority 23)
 *       * Bluedroid Host Stack & A2DP Sink (Priority 20)
 *       * Audio Stream Decoding & I2S Output (Priority 18)
 *       * AVRCP Metadata Callback Task (Priority 6, CONFIG_PROCESS_AVRC_TASK_PRIORITY)
 *   - Core 1 (APP_CPU): Dedicated USB & iPod Protocol Subsystem:
 *       * TinyUSB Device Stack Task (Priority 15)
 *       * USB <-> espod In-Memory Software Bridge Task (Priority 10, CONFIG_USB_ESPOD_BRIDGE_TASK_PRIORITY)
 *       * espod Lingo Protocol Engine Tasks (Priority 2-5)
 * 
 * Inter-Subsystem Data Pipeline:
 *   1. USB -> espod: USB Bulk OUT packets are read from pl2303_usb and fed directly
 *      into espod.processRawBuffer() in RAM.
 *   2. espod -> USB: Packets generated by espod are sent via pl2303_usb_write_bytes().
 *   3. espod -> A2DP: Playback control commands (Play, Pause, Stop, Next, Prev) trigger
 *      playStatusHandler() which invokes a2dp_sink methods on Core 0.
 *   4. A2DP -> espod: AVRCP metadata notifications (Title, Artist, Album, Duration, Position)
 *      update espod state on Core 1 via thread-safe queue.
 * =================================================================================
 */

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "esp_log.h"
#include "esp_system.h"
#include "esp_timer.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"

#include "pl2303_usb.h"
#include "esPod.h"

// AudioTools and ESP32-A2DP components
#include "AudioTools.h"
#include "BluetoothA2DPSink.h"

static const char *TAG = "SUPERPOD_MAIN";

#ifndef ESP_A2D_AUDIO_STATE_REMOTE_SUSPEND
#define ESP_A2D_AUDIO_STATE_REMOTE_SUSPEND ESP_A2D_AUDIO_STATE_SUSPEND
#endif

#pragma region Global Objects and Declarations
I2SStream i2s;
BluetoothA2DPSink a2dp_sink;
esPod espod(1, -1, -1, 19200); // esPod in direct memory ingestion mode (no UART pins required)

struct avrcMetadata
{
    uint8_t id = 0;
    uint8_t *payload = nullptr;
};

QueueHandle_t avrcMetadataQueue = nullptr;
TaskHandle_t processAVRCTaskHandle = nullptr;

void initializeA2DPSink();
esp_err_t initializeAVRCTask();
void connectionStateChanged(esp_a2d_connection_state_t state, void *ptr);
void audioStateChanged(esp_a2d_audio_state_t state, void *ptr);
void avrc_rn_play_pos_callback(uint32_t play_pos);
void avrc_metadata_callback(uint8_t id, const uint8_t *text);
void playStatusHandler(PB_COMMAND playCommand);
#pragma endregion

#pragma region USB to espod In-Memory Software Bridge Task

/**
 * @brief Outbound USB transmit handler callback for forwarding espod response frames to USB Bulk IN endpoint.
 * 
 * @param[in] data Pointer to raw iAP frame bytes.
 * @param[in] len Length of data in bytes.
 */
static void usb_tx_handler(const uint8_t *data, size_t len)
{
    pl2303_usb_write_bytes(data, (uint32_t)len);
}

/**
 * @brief FreeRTOS task bridging USB Bulk OUT data directly to espod raw ringbuffer using event notifications.
 * 
 * @param pvParameters Unused.
 */
static void usb_espod_bridge_task(void *pvParameters)
{
    uint8_t usb_rx_buf[512];

    // Register current task handle to receive TinyUSB Bulk OUT receive notifications
    pl2303_usb_set_rx_task_handle(xTaskGetCurrentTaskHandle());

    while (1)
    {
        // Wait for event notification from TinyUSB Bulk OUT callback (100ms safety timeout)
        ulTaskNotifyTake(pdTRUE, pdMS_TO_TICKS(100));

        // Drain all available raw bytes from TinyUSB Bulk OUT endpoint
        while (1)
        {
            uint32_t rx_bytes = pl2303_usb_read_bytes(usb_rx_buf, sizeof(usb_rx_buf));
            if (rx_bytes == 0)
            {
                break;
            }
            ESP_LOGD(TAG, "USB -> espod: %lu bytes", rx_bytes);
            espod.processRawBuffer(usb_rx_buf, rx_bytes);
        }
    }
}

#pragma endregion

#pragma region AVRCP Queue Processing Task

/**
 * @brief Low-priority task processing AVRCP track metadata items from queue and updating esPod state.
 * 
 * @param pvParameters Unused.
 */
static void processAVRCTask(void *pvParameters)
{
    avrcMetadata incMetadata;

    while (true)
    {
        // Block indefinitely until an AVRCP metadata item is received from the queue
        if (xQueueReceive(avrcMetadataQueue, &incMetadata, portMAX_DELAY) == pdTRUE)
        {
            if (incMetadata.payload != nullptr)
            {
                // Route metadata payload to appropriate esPod state update method
                switch (incMetadata.id)
                {
                case ESP_AVRC_MD_ATTR_ALBUM:
                    espod.updateAlbumName((char *)incMetadata.payload);
                    break;
                case ESP_AVRC_MD_ATTR_ARTIST:
                    espod.updateArtistName((char *)incMetadata.payload);
                    break;
                case ESP_AVRC_MD_ATTR_TITLE:
                    espod.updateTrackTitle((char *)incMetadata.payload);
                    break;
                case ESP_AVRC_MD_ATTR_PLAYING_TIME:
                    espod.updateTrackDuration((uint32_t)atoi((char *)incMetadata.payload));
                    break;
                }
                // Free dynamically allocated payload string after esPod state update
                free(incMetadata.payload);
                incMetadata.payload = nullptr;
            }
        }
    }
}

#pragma endregion

#pragma region Helper Function Definitions

/**
 * @brief Configures I2S DAC GPIO pins and initializes the Bluetooth A2DP Sink with AudioTools I2S output.
 */
void initializeA2DPSink()
{
    // Configure I2S master TX mode with pins defined in Kconfig
    auto config = i2s.defaultConfig(TX_MODE);
    config.pin_bck = CONFIG_I2S_BCLK_PIN;
    config.pin_ws = CONFIG_I2S_WS_PIN;
    config.pin_data = CONFIG_I2S_DOUT_PIN;
    i2s.begin(config);

    // Bind AudioTools I2S stream to BluetoothA2DPSink
    a2dp_sink.set_output(i2s);
    a2dp_sink.set_auto_reconnect(true, 10000);
    a2dp_sink.set_on_connection_state_changed(connectionStateChanged);
    a2dp_sink.set_on_audio_state_changed(audioStateChanged);
    a2dp_sink.set_avrc_metadata_callback(avrc_metadata_callback);
    a2dp_sink.set_avrc_metadata_attribute_mask(ESP_AVRC_MD_ATTR_TITLE | ESP_AVRC_MD_ATTR_ARTIST |
                                               ESP_AVRC_MD_ATTR_ALBUM | ESP_AVRC_MD_ATTR_PLAYING_TIME);
    a2dp_sink.set_avrc_rn_play_pos_callback(avrc_rn_play_pos_callback, 1);

    // Start Bluetooth A2DP Sink service with configured device name
    a2dp_sink.start(CONFIG_A2DP_SINK_NAME);
    ESP_LOGI(TAG, "A2DP Sink started: %s", CONFIG_A2DP_SINK_NAME);
}

/**
 * @brief Initializes AVRCP metadata queue and low-priority processing task.
 * 
 * @return esp_err_t ESP_OK on success, or ESP_FAIL if queue/task creation fails.
 */
esp_err_t initializeAVRCTask()
{
    // Create FreeRTOS queue for buffering incoming AVRCP metadata items
    avrcMetadataQueue = xQueueCreate(CONFIG_AVRC_QUEUE_SIZE, sizeof(avrcMetadata));
    if (avrcMetadataQueue == nullptr)
    {
        ESP_LOGE(TAG, "Failed to create metadata queue");
        return ESP_FAIL;
    }

    // Launch low-priority AVRCP processing task on Core 0 (PRO_CPU)
    xTaskCreatePinnedToCore(processAVRCTask, "processAVRCTask", CONFIG_PROCESS_AVRC_TASK_STACK_SIZE, NULL,
                            CONFIG_PROCESS_AVRC_TASK_PRIORITY, &processAVRCTaskHandle, CONFIG_BT_BLUEDROID_PIN_TO_CORE);
    if (processAVRCTaskHandle == nullptr)
    {
        ESP_LOGE(TAG, "Failed to create processAVRCTask");
        return ESP_FAIL;
    }

    return ESP_OK;
}

#pragma endregion

#pragma region A2DP / AVRCP Callback Definitions

/**
 * @brief Handles Bluetooth A2DP connection state changes.
 * 
 * Enables esPod protocol processing on peer connection, and disables/resets esPod state on disconnection.
 * 
 * @param[in] state Current A2DP connection state (CONNECTED / DISCONNECTED).
 * @param[in] ptr Optional user data pointer (unused).
 */
void connectionStateChanged(esp_a2d_connection_state_t state, void *ptr)
{
    switch (state)
    {
    case ESP_A2D_CONNECTION_STATE_CONNECTED:
        ESP_LOGI(TAG, "ESP_A2D_CONNECTION_STATE_CONNECTED, espod enabled");
        espod.disabled = false;
        a2dp_sink.play();
        break;
    case ESP_A2D_CONNECTION_STATE_DISCONNECTED:
        ESP_LOGI(TAG, "ESP_A2D_CONNECTION_STATE_DISCONNECTED, espod disabled");
        espod.resetState();
        espod.disabled = true;
        break;
    }
}

/**
 * @brief Handles Bluetooth A2DP audio playback state changes (Started / Suspended).
 * 
 * Synchronizes esPod playback status state machine with Bluetooth audio stream state.
 * 
 * @param[in] state Current A2DP audio state (STARTED / REMOTE_SUSPEND).
 * @param[in] ptr Optional user data pointer (unused).
 */
void audioStateChanged(esp_a2d_audio_state_t state, void *ptr)
{
    switch (state)
    {
    case ESP_A2D_AUDIO_STATE_STARTED:
        espod.play(true);
        break;
    case ESP_A2D_AUDIO_STATE_REMOTE_SUSPEND:
        espod.pause(true);
        break;
    default:
        break;
    }
}

/**
 * @brief Handles AVRCP track play position updates from Bluetooth peer.
 * 
 * @param[in] play_pos Current playback position in milliseconds.
 */
void avrc_rn_play_pos_callback(uint32_t play_pos)
{
    espod.updatePlayPosition(play_pos);
    ESP_LOGV(TAG, "Play position: %lu ms", play_pos);
}

/**
 * @brief Handles incoming AVRCP track metadata attributes from Bluetooth peer.
 * 
 * Allocates a copy of the metadata text string and dispatches it to the processing queue.
 * 
 * @param[in] id AVRCP metadata attribute ID (Title, Artist, Album, Duration).
 * @param[in] text Pointer to null-terminated metadata text string.
 */
void avrc_metadata_callback(uint8_t id, const uint8_t *text)
{
    if (text == NULL) return;
    if ((id != ESP_AVRC_MD_ATTR_PLAYING_TIME) && (text[0] == '\0')) return;

    // Allocate copy of metadata text payload for queue transfer
    avrcMetadata incMetadata;
    incMetadata.id = id;
    incMetadata.payload = (uint8_t *)strdup((const char *)text);

    if (incMetadata.payload == nullptr) return;

    // Push item to AVRCP metadata processing queue; free memory if queue is full
    if (xQueueSend(avrcMetadataQueue, &incMetadata, 0) != pdTRUE)
    {
        free(incMetadata.payload);
    }
}

/**
 * @brief Callback handler invoked by esPod when host sends iAP playback control commands.
 * 
 * Maps iAP playback commands (Play, Pause, Stop, Next, Prev) directly to Bluetooth A2DPSink methods.
 * 
 * @param[in] playCommand Target playback command enum value.
 */
void playStatusHandler(PB_COMMAND playCommand)
{
    switch (playCommand)
    {
    case PB_CMD_STOP:
        a2dp_sink.stop();
        ESP_LOGD(TAG, "A2DP_STOP");
        break;
    case PB_CMD_PLAY:
        a2dp_sink.play();
        ESP_LOGD(TAG, "A2DP_PLAY");
        break;
    case PB_CMD_PAUSE:
        a2dp_sink.pause();
        ESP_LOGD(TAG, "A2DP_PAUSE");
        break;
    case PB_CMD_PREVIOUS_TRACK:
    case PB_CMD_PREV:
        a2dp_sink.previous();
        ESP_LOGD(TAG, "A2DP_PREV");
        break;
    case PB_CMD_NEXT_TRACK:
    case PB_CMD_NEXT:
        a2dp_sink.next();
        ESP_LOGD(TAG, "A2DP_NEXT");
        break;
    default:
        break;
    }
}

#pragma endregion

#pragma region Main Entry Point

/**
 * @brief Main application entry point for superPod firmware.
 * 
 * Orchestrates dual-core initialization (Option B Swapped):
 *   - Core 1: TinyUSB PL2303 driver, esPod handlers, and direct in-memory software bridge task.
 *   - Core 0: AVRCP metadata task and Bluetooth A2DP Sink with AudioTools I2S output.
 */
extern "C" void app_main(void)
{
    ESP_LOGI(TAG, "superPod firmware starting up on ESP32-S31...");
    ESP_LOGI(TAG, "Reset reason: %d", esp_reset_reason());

    // Step 1: Initialize TinyUSB PL2303 Device Driver on Core 1 (APP_CPU)
    ESP_ERROR_CHECK(pl2303_usb_init(CONFIG_TINYUSB_TASK_CORE));

    // Step 2: Attach playback controller and outbound USB TX callbacks to espod
    espod.attachPlayControlHandler(playStatusHandler);
    espod.attachTxHandler(usb_tx_handler);
    espod.resetState();

    // Step 3: Start USB <-> espod bridge task on Core 1 (APP_CPU)
    xTaskCreatePinnedToCore(usb_espod_bridge_task, "usb_espod_bridge", CONFIG_USB_ESPOD_BRIDGE_TASK_STACK_SIZE,
                            NULL, CONFIG_USB_ESPOD_BRIDGE_TASK_PRIORITY, NULL, CONFIG_TINYUSB_TASK_CORE);

    // Step 4: Initialize AVRCP task & Bluetooth A2DP Sink on Core 0 (PRO_CPU)
    if (initializeAVRCTask() != ESP_OK)
    {
        ESP_LOGE(TAG, "AVRC Task init failed");
        esp_restart();
    }

    // Step 5: Start A2DP Sink audio streaming pipeline
    initializeA2DPSink();

    ESP_LOGI(TAG, "superPod initialization completed. Waiting for Bluetooth peer connection...");
}

#pragma endregion

